apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-noticias-deployment
  # labels:
  #   app: portal-noticias
spec:
  template:
    metadata:
      name: portal-noticias
      labels:
        app: portal-noticias
    spec:
      containers:
        - name: portal-noticias-container
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portal-configmap
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          resoucers:
            requests:
              cpu: 10m # 10 milicores de cpu  para funcionar
  replicas: 3
  selector:
    matchLabels:
      app: portal-noticias