apiVersion: v1
kind: Pod
metadata:
  name: pod-pv
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume-dentro-do-container
          name: primeiro-pv
    # - name: jenkins-container
    #   image: jenkins:alpine
    #   volumeMounts:
    #     - mountPath: /volume-dentro-do-container
    #       name: primeiro-volume
  volumes:
    - name: primeiro-pv
      persistentVolumeClain:
        clainName: pvc-1

        